window.ACTIVITY_CONFIG={
  defaultLocale:"en",
  supportedLocales:["en","id-ID","fr-FR","ar"],
  heroAsset:"./assets/hero-reward-main.jpg",
  privateChatGuideUrl:"https://boloup.github.io/app-tutorial-pages/private-chat-recruitment-tutorial/dist/{locale}/",
  locales:{
    en:{dir:"ltr",title:"Invite & Recruit Rewards Guide",heroPrefix:"Up to",heroAmount:"$30",heroSuffix:"per Eligible New Host",heroSub:"Inviter Bonus + Recruiter Bonus",heroNote:"Rewards are cumulative and conditional.",noticeTitle:"New Campaign, Clearer Reward Attribution",noticeText:"New-user acquisition and in-app host conversion now earn different bonuses.",decisionTitle:"Which User Did You Bring?",question:"Is this their first BoloUp account?",yes:"YES",no:"NO",newTitle:"New User from Outside BoloUp",newPill:"INVITER BONUS",newText:"The Invite relationship must be created during first download/registration through an official invite path.",newExtra:"+ Recruiter Bonus when a valid Recruit relationship is also established.",existingTitle:"Existing User Already in BoloUp",existingPill:"RECRUITER BONUS ONLY",existingText:"Convert the user into a host and recruit them into an Agency through an official method.",existingExtra:"No inviter can be added after registration.",whyTitle:"Why the Rewards Are Different",whyText:"Inviter Bonus rewards eligible new-user acquisition. Recruiter Bonus rewards in-app host conversion and Agency recruitment.",before:"Before:",beforeText:"one reward package + post-registration binding",now:"Now:",nowText:"separate bonuses + official paths only",warningTitle:"Inviter Binding Is Locked After Registration",warningText:"Once account registration succeeds, the inviter relationship cannot be manually added or changed.",cta:"View Private Chat Recruitment Guide",
      faq:[
        {q:"Which invitation method should I use?",a:"Use an official method that matches the user’s status. Invite Now is for eligible new-user acquisition. Private Chat can recruit a user into the sender’s Agency after the user has replied at least once. Host Invite (ID) and Host Invite (Link) are available only to Agents."},
        {q:"Can I bind or change my inviter after registration?",a:"No. Once registration succeeds, the inviter cannot be added or changed. If an inviter-binding step appears during registration in a future app version, it must be completed before the account is created."},
        {q:"Why do existing users receive Recruiter Bonus only?",a:"An existing BoloUp account is not a new-user acquisition. Converting that user into a host and recruiting them into an Agency can therefore generate Recruiter Bonus only."},
        {q:"Can one new host generate both bonuses?",a:"Yes. An eligible new user may generate Inviter Bonus through a valid official invite relationship and Recruiter Bonus when a valid Recruit relationship is also established. Each bonus still depends on its own task and eligibility rules."},
        {q:"Who can use Host Invite features?",a:"Host Invite (ID) and Host Invite (Link) are Agent-only. Host Invite (Link) can establish an Invite relationship only when the linked user meets the new-user standard and completes first download/registration; it can also establish a Recruit relationship when the user first joins the Agent’s Agency. Hosts and Agents can use Private Chat recruitment."}
      ]},
    "id-ID":{dir:"ltr",title:"Panduan Reward Undang & Rekrut",heroPrefix:"Hingga",heroAmount:"$30",heroSuffix:"per Host Baru yang Memenuhi Syarat",heroSub:"Bonus Pengundang + Bonus Perekrut",heroNote:"Reward bersifat kumulatif dan memiliki ketentuan.",noticeTitle:"Campaign Baru, Atribusi Reward Lebih Jelas",noticeText:"Akuisisi pengguna baru dan konversi host di aplikasi kini memperoleh bonus yang berbeda.",decisionTitle:"Pengguna Mana yang Anda Bawa?",question:"Apakah ini akun BoloUp pertama mereka?",yes:"YA",no:"TIDAK",newTitle:"Pengguna Baru dari Luar BoloUp",newPill:"BONUS PENGUNDANG",newText:"Hubungan Invite harus dibuat saat unduhan/pendaftaran pertama melalui jalur undangan resmi.",newExtra:"+ Bonus Perekrut jika hubungan Recruit yang valid juga terbentuk.",existingTitle:"Pengguna yang Sudah Ada di BoloUp",existingPill:"HANYA BONUS PEREKRUT",existingText:"Ubah pengguna menjadi host dan rekrut mereka ke Agency melalui metode resmi.",existingExtra:"Pengundang tidak dapat ditambahkan setelah pendaftaran.",whyTitle:"Mengapa Reward Berbeda",whyText:"Bonus Pengundang memberi reward untuk akuisisi pengguna baru yang memenuhi syarat. Bonus Perekrut memberi reward untuk konversi host dan perekrutan Agency.",before:"Sebelumnya:",beforeText:"satu paket reward + binding setelah pendaftaran",now:"Sekarang:",nowText:"bonus terpisah + hanya jalur resmi",warningTitle:"Binding Pengundang Terkunci Setelah Pendaftaran",warningText:"Setelah pendaftaran akun berhasil, hubungan pengundang tidak dapat ditambahkan atau diubah secara manual.",cta:"Lihat Panduan Rekrutmen Private Chat",
      faq:[
        {q:"Metode undangan mana yang harus saya gunakan?",a:"Gunakan metode resmi yang sesuai dengan status pengguna. Invite Now untuk akuisisi pengguna baru yang memenuhi syarat. Private Chat dapat merekrut pengguna ke Agency pengirim setelah pengguna membalas setidaknya satu pesan. Host Invite (ID) dan Host Invite (Link) hanya tersedia untuk Agent."},
        {q:"Bisakah saya binding atau mengganti pengundang setelah pendaftaran?",a:"Tidak. Setelah pendaftaran berhasil, pengundang tidak dapat ditambahkan atau diganti. Jika langkah binding pengundang muncul selama pendaftaran pada versi aplikasi mendatang, selesaikan sebelum akun dibuat."},
        {q:"Mengapa pengguna lama hanya mendapat Bonus Perekrut?",a:"Akun BoloUp yang sudah ada bukan akuisisi pengguna baru. Mengubah pengguna tersebut menjadi host dan merekrutnya ke Agency hanya dapat menghasilkan Bonus Perekrut."},
        {q:"Bisakah satu host baru menghasilkan kedua bonus?",a:"Ya. Pengguna baru yang memenuhi syarat dapat menghasilkan Bonus Pengundang melalui hubungan Invite resmi yang valid dan Bonus Perekrut jika hubungan Recruit yang valid juga terbentuk. Setiap bonus tetap mengikuti tugas dan syaratnya sendiri."},
        {q:"Siapa yang dapat menggunakan fitur Host Invite?",a:"Host Invite (ID) dan Host Invite (Link) hanya untuk Agent. Host Invite (Link) hanya membentuk hubungan Invite jika pengguna memenuhi standar pengguna baru dan menyelesaikan unduhan/pendaftaran pertama. Fitur ini juga dapat membentuk hubungan Recruit saat pengguna pertama kali bergabung ke Agency Agent. Host dan Agent dapat menggunakan rekrutmen Private Chat."}
      ]},
    "fr-FR":{dir:"ltr",title:"Guide des récompenses d’invitation et de recrutement",heroPrefix:"Jusqu’à",heroAmount:"30 $",heroSuffix:"par nouvel hôte éligible",heroSub:"Bonus d’invitation + Bonus de recrutement",heroNote:"Les récompenses sont cumulatives et conditionnelles.",noticeTitle:"Nouvelle campagne, attribution plus claire",noticeText:"L’acquisition de nouveaux utilisateurs et la conversion d’hôtes dans l’application donnent désormais des bonus différents.",decisionTitle:"Quel utilisateur avez-vous amené ?",question:"S’agit-il de son premier compte BoloUp ?",yes:"OUI",no:"NON",newTitle:"Nouvel utilisateur venant de l’extérieur",newPill:"BONUS D’INVITATION",newText:"La relation Invite doit être créée lors du premier téléchargement/de la première inscription via une méthode officielle.",newExtra:"+ Bonus de recrutement si une relation Recruit valide est également établie.",existingTitle:"Utilisateur déjà présent sur BoloUp",existingPill:"BONUS DE RECRUTEMENT UNIQUEMENT",existingText:"Convertissez l’utilisateur en hôte et recrutez-le dans une Agency via une méthode officielle.",existingExtra:"Aucun invitant ne peut être ajouté après l’inscription.",whyTitle:"Pourquoi les récompenses diffèrent",whyText:"Le Bonus d’invitation récompense l’acquisition de nouveaux utilisateurs éligibles. Le Bonus de recrutement récompense la conversion en hôte et le recrutement dans une Agency.",before:"Avant :",beforeText:"un seul pack + liaison après inscription",now:"Maintenant :",nowText:"bonus séparés + méthodes officielles",warningTitle:"La liaison de l’invitant est verrouillée après l’inscription",warningText:"Une fois l’inscription réussie, l’invitant ne peut plus être ajouté ni modifié manuellement.",cta:"Voir le guide de recrutement par chat privé",
      faq:[
        {q:"Quelle méthode d’invitation dois-je utiliser ?",a:"Utilisez une méthode officielle adaptée au statut de l’utilisateur. Invite Now sert à acquérir un nouvel utilisateur éligible. Le chat privé permet de recruter un utilisateur dans l’Agency de l’expéditeur après au moins une réponse. Host Invite (ID) et Host Invite (Link) sont réservés aux Agents."},
        {q:"Puis-je lier ou modifier mon invitant après l’inscription ?",a:"Non. Une fois l’inscription réussie, l’invitant ne peut plus être ajouté ni modifié. Si une étape de liaison apparaît pendant l’inscription dans une future version, elle devra être terminée avant la création du compte."},
        {q:"Pourquoi les utilisateurs existants ne reçoivent-ils que le Bonus de recrutement ?",a:"Un compte BoloUp existant n’est pas une acquisition de nouvel utilisateur. Sa conversion en hôte et son recrutement dans une Agency ne peuvent donc générer que le Bonus de recrutement."},
        {q:"Un nouvel hôte peut-il générer les deux bonus ?",a:"Oui. Un nouvel utilisateur éligible peut générer le Bonus d’invitation via une relation Invite officielle valide, puis le Bonus de recrutement si une relation Recruit valide est aussi établie. Chaque bonus conserve ses propres tâches et conditions."},
        {q:"Qui peut utiliser les fonctions Host Invite ?",a:"Host Invite (ID) et Host Invite (Link) sont réservés aux Agents. Host Invite (Link) établit une relation Invite uniquement si l’utilisateur est nouveau et termine son premier téléchargement/inscription. Il peut aussi établir une relation Recruit lorsque l’utilisateur rejoint pour la première fois l’Agency de l’Agent. Les hôtes et Agents peuvent recruter par chat privé."}
      ]},
    ar:{dir:"rtl",title:"دليل مكافآت الدعوة والاستقطاب",heroPrefix:"حتى",heroAmount:"30$",heroSuffix:"لكل مضيف جديد مؤهل",heroSub:"مكافأة الدعوة + مكافأة الاستقطاب",heroNote:"المكافآت تراكمية ومشروطة.",noticeTitle:"حملة جديدة ونَسب أوضح للمكافآت",noticeText:"أصبح اكتساب المستخدمين الجدد وتحويل مستخدمي التطبيق إلى مضيفين يمنحان مكافآت مختلفة.",decisionTitle:"أي مستخدم قمت بجلبه؟",question:"هل هذا أول حساب BoloUp له؟",yes:"نعم",no:"لا",newTitle:"مستخدم جديد من خارج BoloUp",newPill:"مكافأة الدعوة",newText:"يجب إنشاء علاقة Invite أثناء التنزيل/التسجيل الأول عبر طريقة دعوة رسمية.",newExtra:"+ مكافأة الاستقطاب عند إنشاء علاقة Recruit صالحة أيضًا.",existingTitle:"مستخدم موجود بالفعل في BoloUp",existingPill:"مكافأة الاستقطاب فقط",existingText:"حوّل المستخدم إلى مضيف واستقطبه إلى Agency عبر طريقة رسمية.",existingExtra:"لا يمكن إضافة داعٍ بعد اكتمال التسجيل.",whyTitle:"لماذا تختلف المكافآت",whyText:"تكافئ مكافأة الدعوة اكتساب مستخدمين جدد مؤهلين. وتكافئ مكافأة الاستقطاب تحويل مستخدمي التطبيق إلى مضيفين واستقطابهم إلى Agency.",before:"سابقًا:",beforeText:"حزمة مكافآت واحدة + ربط بعد التسجيل",now:"الآن:",nowText:"مكافآت منفصلة + الطرق الرسمية فقط",warningTitle:"يُقفل ربط الداعي بعد التسجيل",warningText:"بعد نجاح تسجيل الحساب، لا يمكن إضافة الداعي أو تغييره يدويًا.",cta:"عرض دليل الاستقطاب عبر الدردشة الخاصة",
      faq:[
        {q:"أي طريقة دعوة يجب أن أستخدم؟",a:"استخدم طريقة رسمية تناسب حالة المستخدم. Invite Now مخصص لاكتساب مستخدم جديد مؤهل. ويمكن عبر الدردشة الخاصة استقطاب المستخدم إلى Agency المرسل بعد أن يرد برسالة واحدة على الأقل. أما Host Invite (ID) وHost Invite (Link) فهما متاحان للـAgent فقط."},
        {q:"هل يمكنني ربط الداعي أو تغييره بعد التسجيل؟",a:"لا. بعد نجاح التسجيل لا يمكن إضافة الداعي أو تغييره. وإذا ظهرت خطوة ربط الداعي أثناء التسجيل في إصدار مستقبلي، فيجب إكمالها قبل إنشاء الحساب."},
        {q:"لماذا يحصل المستخدمون الحاليون على مكافأة الاستقطاب فقط؟",a:"الحساب الموجود بالفعل في BoloUp لا يُعد اكتساب مستخدم جديد. لذلك فإن تحويله إلى مضيف واستقطابه إلى Agency يمكن أن يمنح مكافأة الاستقطاب فقط."},
        {q:"هل يمكن لمضيف جديد واحد تحقيق المكافأتين؟",a:"نعم. يمكن للمستخدم الجديد المؤهل تحقيق مكافأة الدعوة عبر علاقة Invite رسمية صالحة، وتحقيق مكافأة الاستقطاب أيضًا عند إنشاء علاقة Recruit صالحة. وتظل لكل مكافأة مهامها وشروطها الخاصة."},
        {q:"من يمكنه استخدام ميزات Host Invite؟",a:"Host Invite (ID) وHost Invite (Link) متاحان للـAgent فقط. ولا ينشئ Host Invite (Link) علاقة Invite إلا إذا استوفى المستخدم معيار المستخدم الجديد وأكمل أول تنزيل/تسجيل. ويمكنه أيضًا إنشاء علاقة Recruit عند انضمام المستخدم لأول مرة إلى Agency الخاصة بالـAgent. ويمكن للمضيفين والـAgents استخدام الاستقطاب عبر الدردشة الخاصة."}
      ]}
  }
};
